const userRouter = require('./userRouter/userRouter')
const loginRouter = require('./authRouter/loginRouter')
const materialRouter = require('./materialRouter/materialRouter')
const productRouter = require('./productRouter/productRouter')
const logoutRouter = require('./authRouter/logoutRouter')
const reportRouter = require('./reportRouter/reportRouter')
const dashboardRouter = require('./dashboardRouter/dashboardRouter')
const helperRouter = require('./helperRouter/helperRouter')
const { jwtAccessMiddleware } = require('../middlewares/jwt-access-middleware')

exports.appRouter = (app) => {
    app.get('/', helperRouter)
    app.use('/api', jwtAccessMiddleware, helperRouter)
    app.use('/api', loginRouter)
    app.use('/api', jwtAccessMiddleware, logoutRouter)
    app.use('/api', jwtAccessMiddleware, userRouter)
    app.use('/api', jwtAccessMiddleware, materialRouter)
    app.use('/api', jwtAccessMiddleware, productRouter)
    app.use('/api', jwtAccessMiddleware, reportRouter)
    app.use('/api', jwtAccessMiddleware, dashboardRouter)
}